// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqtaecohxwsnjozmcqcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxdGFlY29oeHdzbmpvem1jcWN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTc2NjYsImV4cCI6MjA2NDI5MzY2Nn0.FFHgPj3IbUep6cohXQllGct6M0mcJkjQ56_WS3BMkEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);